name: minecraft-shop-lands
version: '1.0'
main: com.mochiserver.minecraftShopLands.MinecraftShopLands
api-version: '1.21'
authors: [ mtmtyu ]
description: 土地管理システムプラグイン
depend: [WorldGuard]
commands:
  createshop:
    description: 選択範囲に土地を作成します
    usage: /createshop
    permission: shoplands.create
permissions:
  shoplands.create:
    description: 土地を作成する権限
    default: op
  shoplands.buy:
    description: 土地を購入する権限
    default: true
  shoplands.admin:
    description: 管理者権限
    default: op
