name: minecraft-shop-lands
version: '1.0'
main: com.mochiserver.minecraftShopLands.MinecraftShopLands
api-version: '1.21'
authors: [ mtmtyu ]
description: 土地管理システムプラグイン
depend: [WorldGuard]
commands:
  createshop:
    description: 選択範囲に土地を作成します
    usage: /createshop
    permission: shoplands.create
  renameland:
    description: 土地の名前を変更します
    usage: /renameland <現在の土地名> <新しい土地名>
    permission: shoplands.create
  landinfo:
    description: 自分の所有土地を表示します
    usage: /landinfo
  resetland:
    description: 指定プレイヤーの土地所有権をリセットします
    usage: /resetland <プレイヤー名>
    permission: shoplands.admin
permissions:
  shoplands.create:
    description: 土地を作成する権限
    default: op
  shoplands.buy:
    description: 土地を購入する権限
    default: true
  shoplands.admin:
    description: 管理者権限
    default: op
