name: minecraft-shop-lands
version: '1.0'
main: com.mochiserver.minecraftShopLands.MinecraftShopLands
api-version: '1.21'
authors: [ mtmtyu ]
description: 土地管理システムプラグイン
depend: [WorldGuard]
commands:
  createshop:
    description: 選択範囲に土地を作成します
    usage: /createshop
